# Generated by Django 5.1.2 on 2024-10-14 14:29

import products.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('picture', models.ImageField(height_field='image_height', upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение', width_field='image_width')),
                ('image_width', models.PositiveIntegerField(editable=False, verbose_name='Ширина')),
                ('image_height', models.PositiveIntegerField(editable=False, verbose_name='Высота')),
                ('content', models.TextField(max_length=600, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[products.custom_validators.PositiveDecimalValidator(decimal_places=2, max_digits=10)], verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
