# Generated by Django 5.1.2 on 2024-10-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_dt',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата оплаты'),
        ),
    ]
