# Generated by Django 5.1.2 on 2024-10-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(default='Bank Bill', max_length=25, verbose_name='Тип оплаты'),
        ),
    ]
